name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build Debug
      run: swift build -v
    
    - name: Build Release
      run: swift build -c release -v
    
    - name: Run tests
      run: swift test
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScrollControl
        path: .build/release/ScrollControl