name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build ScrollControl
      run: |
        swift build -c release
        
    - name: Create release bundle
      run: |
        mkdir -p ScrollControl-release
        cp .build/release/ScrollControl ScrollControl-release/
        cp README.md ScrollControl-release/
        cp LICENSE ScrollControl-release/
        
        # Create simplified install script for pre-built binary
        cat > ScrollControl-release/install.sh << 'EOF'
        #!/bin/bash
        
        # Installation script for ScrollControl (pre-built binary)
        
        APP_NAME="ScrollControl"
        INSTALL_DIR="$HOME/Applications"
        LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
        PLIST_NAME="com.scrollcontrol.app.plist"
        
        echo "Installing ScrollControl..."
        
        # Create Applications directory if it doesn't exist
        mkdir -p "$INSTALL_DIR"
        
        # Copy the app to Applications
        cp "./ScrollControl" "$INSTALL_DIR/"
        chmod +x "$INSTALL_DIR/ScrollControl"
        
        echo "✅ App installed to $INSTALL_DIR/ScrollControl"
        
        # Create LaunchAgent plist for auto-startup
        mkdir -p "$LAUNCH_AGENTS_DIR"
        
        cat > "$LAUNCH_AGENTS_DIR/$PLIST_NAME" << PLIST_EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>Label</key>
            <string>com.scrollcontrol.app</string>
            <key>ProgramArguments</key>
            <array>
                <string>$INSTALL_DIR/ScrollControl</string>
            </array>
            <key>RunAtLoad</key>
            <true/>
            <key>StandardOutPath</key>
            <string>$HOME/Library/Logs/ScrollControl.log</string>
            <key>StandardErrorPath</key>
            <string>$HOME/Library/Logs/ScrollControl.log</string>
        </dict>
        </plist>
        PLIST_EOF
        
        # Load the LaunchAgent
        if ! launchctl bootstrap gui/$(id -u) "$LAUNCH_AGENTS_DIR/$PLIST_NAME" 2>/dev/null; then
            launchctl load "$LAUNCH_AGENTS_DIR/$PLIST_NAME" 2>/dev/null || true
        fi
        
        echo "✅ Auto-startup configured"
        echo ""
        echo "ScrollControl is now installed and will start automatically at login."
        echo "You may need to grant accessibility permissions in System Settings."
        EOF
        
        chmod +x ScrollControl-release/install.sh
        cp uninstall.sh ScrollControl-release/
        
    - name: Create archive
      run: |
        tar -czf ScrollControl-macOS.tar.gz ScrollControl-release/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScrollControl-macOS
        path: ScrollControl-macOS.tar.gz
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ScrollControl-macOS.tar.gz
        body: |
          ## ScrollControl Release
          
          **Pre-built binary included - no compilation required!**
          
          ### Quick Installation
          1. Download and extract `ScrollControl-macOS.tar.gz`
          2. Run `./install.sh` to install and setup auto-startup
          3. Grant accessibility permissions when prompted
          
          ### Manual Installation
          1. Download and extract `ScrollControl-macOS.tar.gz`
          2. Run `./ScrollControl` directly (no auto-startup)
          3. Grant accessibility permissions when prompted
          
          ### Features
          - Independent scroll direction control for trackpad and mouse wheel
          - Clean menu bar dropdown (no popover arrow)
          - Persistent settings storage
          - Auto-startup configuration with install script
          
          ### Requirements
          - macOS 12.0 or later
          - Accessibility permissions required for scroll event monitoring
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}