name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build ScrollControl
      run: |
        swift build -c release
        
    - name: Create release bundle
      run: |
        mkdir -p ScrollControl-release
        cp .build/release/ScrollControl ScrollControl-release/
        cp README.md ScrollControl-release/
        cp LICENSE ScrollControl-release/
        cp build.sh ScrollControl-release/
        cp install.sh ScrollControl-release/
        cp uninstall.sh ScrollControl-release/
        cp test.sh ScrollControl-release/
        
    - name: Create archive
      run: |
        tar -czf ScrollControl-macOS.tar.gz ScrollControl-release/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ScrollControl-macOS
        path: ScrollControl-macOS.tar.gz
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ScrollControl-macOS.tar.gz
        body: |
          ## ScrollControl Release
          
          ### Installation
          1. Download and extract `ScrollControl-macOS.tar.gz`
          2. Run `./build.sh` to build the app
          3. Run `./install.sh` to install and setup auto-startup
          4. Grant accessibility permissions when prompted
          
          ### Manual Installation
          1. Run `./build.sh` to build
          2. Run `.build/release/ScrollControl` directly
          
          ### Features
          - Independent scroll direction control for trackpad and mouse wheel
          - Menu bar integration with clean dropdown menu
          - Persistent settings storage
          - Auto-startup configuration
          
          ### Requirements
          - macOS 12.0 or later
          - Accessibility permissions required
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}